### ISSUE TITLE
Error with Slicer 4.11.

### ISSUE THREAD

**Issue by Horviratus** [MedicalImageAnalysisTutorials/SlicerCochlea#33]
I get this error:

Traceback (most recent call last):
  File "D:/Programok/Slicer 4.11.20210226/NA-MIC/Extensions-29738/SlicerCochlea/lib/Slicer-4.11/qt-scripted-modules/CochleaSeg.py", line 240, in onApplyBtnClick
    self.logic.run( self.inputSelectorCoBx.currentNode(),self.logic.inputFiducialNode, self.vsc.vtVars['cochleaSide'] )
  File "D:/Programok/Slicer 4.11.20210226/NA-MIC/Extensions-29738/SlicerCochlea/lib/Slicer-4.11/qt-scripted-modules/CochleaSeg.py", line 315, in run
    self.vsc.vtVars['intputCropPath'] = self.vsc.runCropping(inputVolumeNode, inputPointT,self.vsc.vtVars['croppingLength'],  self.vsc.vtVars['RSxyz'],  self.vsc.vtVars['hrChk'],0)
  File "D:\Programok\Slicer 4.11.20210226\NA-MIC\Extensions-29738\SlicerCochlea\lib\Slicer-4.11\qt-scripted-modules\VisSimCommon.py", line 449, in runCropping
    croppedImage = cropper.Execute(inputImage, croppingBounds[0], croppingBounds[1])
TypeError: Execute() takes 2 positional arguments but 4 were given

**Comment by idhamari** [comment]
Sorry for the late reply. 

I will try to update the code soon to the recent Slicer version.

**Comment by idhamari** [comment]
https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/commit/c2ca13cc83e96873697b46e6ebd90492295c9000
