### ISSUE TITLE
Typo leading to file not found

### ISSUE THREAD

**Issue by FS-1983** [MedicalImageAnalysisTutorials/SlicerCochlea#41]
hi, thanks for creating and maintaining this amazing tool. When setting it up, I however got the following error message:

`Processing started
CASE_1_MRI_ISO
CASE1_1_CT_ISO
Defaults paths: 
VisSimTools folder: C:\Users\Flori\VisSimTools
Output folder : C:\Users\Flori\VisSimTools\outputs
elastix binaries are found in C:\ProgramData\NA-MIC\Slicer 5.0.3\NA-MIC\Extensions-30893\SlicerElastix\lib\Slicer-5.0/elastix.exe
Cochlea Extension is selected
sha256computedCheckSum: d9db4206e2b0abdbf9a160cecde47eedc9da2cc593ce8601900d47c4c05de422
Models or contents are wrong, trying to download ...
Downloading VisSim Tools ... 
Downloading VisSimTools others ...
Extracting to user home 
Error: can not download and extract VisSimTools ...
Destination path 'C:\Users\Flori/VisSimTools\VisSimToolsCochlea' already exists
0
<class 'vtkSlicerMarkupsModuleMRML.vtkMRMLMarkupsFiducialNode'>
run fixed point: ============================
CASE_1_MRI_ISO
[482 355 72]
0
<class 'vtkSlicerMarkupsModuleMRML.vtkMRMLMarkupsFiducialNode'>
run moving point: ============================
CASE1_1_CT_ISO
[717 621 123]
=================== Cropping =====================
================= Begin cropping ... =====================
location: [482,355,72] cropping length: [ 10 , 10 , 10 ]
[ 10 , 10 , 10 ]
[ 0.125, 0.125 , 0.125 ]
[482,355,72]
location: [482.0, 355.0, 72.0] cropping length: [10.0, 10.0, 10.0]
Cropping with [458, 331, 48] and [144, 271, 54].
cropped: C:\Users\Flori\VisSimTools\CASE_1_MRI_ISO_Crop.nrrd
iso cropped: C:\Users\Flori\VisSimTools\CASE_1_MRI_ISO_CropIso.nrrd
C:\ProgramData\NA-MIC\Slicer 5.0.3\Slicer --launch C:\ProgramData\NA-MIC\Slicer 5.0.3\lib\Slicer-4.11\cli-modules\ResampleScalarVolume
Traceback (most recent call last):
File "C:/ProgramData/NA-MIC/Slicer 5.0.3/NA-MIC/Extensions-30893/SlicerCochlea/lib/Slicer-5.0/qt-scripted-modules/CochleaReg.py", line 219, in onApplyBtnClick
registeredMovingVolumeNode =self.logic.run( self.fixedSelectorCoBx.currentNode(),self.fixedFiducialNode, self.movingSelectorCoBx.currentNode(),self.movingFiducialNode )
File "C:/ProgramData/NA-MIC/Slicer 5.0.3/NA-MIC/Extensions-30893/SlicerCochlea/lib/Slicer-5.0/qt-scripted-modules/CochleaReg.py", line 309, in run
self.vsc.vtVars['fixedCropPath'] = self.vsc.runCropping(fixedVolumeNode, fixedPointT,self.vsc.vtVars['croppingLength'], self.vsc.vtVars['RSxyz'], self.vsc.vtVars['hrChk'],0)
File "C:\ProgramData\NA-MIC\Slicer 5.0.3\NA-MIC\Extensions-30893\SlicerCochlea\lib\Slicer-5.0\qt-scripted-modules\VisSimCommon.py", line 490, in runCropping
print(os.path.getsize(resamplingCommand))
File "C:\ProgramData/NA-MIC/Slicer 5.0.3/bin/../lib/Python/Lib\genericpath.py", line 50, in getsize
return os.stat(filename).st_size
FileNotFoundError: [WinError 3] Het systeem kan het opgegeven pad niet vinden: 'C:\\ProgramData\\NA-MIC\\Slicer 5.0.3\\lib\\Slicer-4.11\\cli-modules\\ResampleScalarVolume.exe'
`

This error message does not appear anymore when I chance "Slicer-4.11" to "Slicer-5.0" on line 474 in VisSimCommon.py

After this change, I did have different errors though.. which I will post in a different issue for clarity.

**Comment by FS-1983** [comment]
to add, this happened on Win10 using slicer 5.0.3
